export const SET_SIGNUP = 'SET_SIGNUP';
export const SET_LOGIN = 'SET_LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_AUTH = 'SET_AUTH';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';

export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const SET_PROJECTS = 'SET_PROJECTS';

export const SET_LIBRARY = 'SET_LIBRARY';
export const SET_MYPROJECT = 'SET_MYPROJECT';
export const SET_NEWPROJECT = 'SET_NEWPROJECT';

export const SET_STATISTICS = 'SET_STATISTICS';
export const UPDATE_STATISTICS = 'UPDATE_STATISTICS';

export const FAVORITES = 'FAVORITES';
export const UPDATE_CONNECTIONS = 'UPDATE_CONNECTIONS';

export const ADD_NODE = 'ADD_NODE';
export const UPDATE_NODE = 'UPDATE_NODE';
export const FIRST_NODE = 'FIRST_NODE';
export const GET_NODES = 'GET_NODES';
export const DELETE_NODE = 'DELETE_NODE';

export const SET_PROJECT_FOR_EDIT = 'SET_PROJECT_FOR_EDIT';

export const SET_NODES_FOREDIT = 'SET_NODES_FOREDIT';
